# Generated by Django 4.1.7 on 2023-03-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_eq_borrow', '0005_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
