# Generated by Django 4.1.7 on 2023-03-12 16:19

from django.db import migrations, models
import django.db.models.deletion
import lab_eq_borrow.storages


class Migration(migrations.Migration):

    dependencies = [
        ('lab_eq_borrow', '0006_alter_user_u_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_statuse',
            new_name='Borrow_status',
        ),
        migrations.RenameModel(
            old_name='Item_categorie',
            new_name='Faculty',
        ),
        migrations.RenameModel(
            old_name='Borrow_statuse',
            new_name='Item_category',
        ),
        migrations.RenameModel(
            old_name='Facultie',
            new_name='Item_status',
        ),
        migrations.RenameField(
            model_name='borrow_status',
            old_name='item_status_id',
            new_name='b_status_id',
        ),
        migrations.RenameField(
            model_name='borrow_status',
            old_name='item_status_name',
            new_name='b_status_name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='item_cate_id',
            new_name='f_id',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='item_cate_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='item_category',
            old_name='b_status_id',
            new_name='item_cate_id',
        ),
        migrations.RenameField(
            model_name='item_category',
            old_name='b_status_name',
            new_name='item_cate_name',
        ),
        migrations.RenameField(
            model_name='item_status',
            old_name='f_id',
            new_name='item_status_id',
        ),
        migrations.RenameField(
            model_name='item_status',
            old_name='f_name',
            new_name='item_status_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_img_id',
        ),
        migrations.AddField(
            model_name='item',
            name='item_img_url',
            field=models.FileField(blank=True, null=True, storage=lab_eq_borrow.storages.MediaStorage, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='borrow_info',
            name='b_item',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.item'),
        ),
        migrations.AlterField(
            model_name='borrow_info',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.user'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='borrow_info',
            table='borrow_infos',
        ),
        migrations.AlterModelTable(
            name='borrow_status',
            table='borrow_statuses',
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='faculties',
        ),
        migrations.AlterModelTable(
            name='id_type',
            table='id_types',
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
        migrations.AlterModelTable(
            name='item_category',
            table='item_categories',
        ),
        migrations.AlterModelTable(
            name='item_status',
            table='item_statuses',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='user_privilege',
            table='user_privileges',
        ),
    ]
