# Generated by Django 4.1.7 on 2023-03-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_eq_borrow', '0007_rename_item_statuse_borrow_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_borrow_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.borrow_status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.item_category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.faculty'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.item_status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='lab_eq_borrow.faculty'),
        ),
        migrations.AlterModelTable(
            name='borrow_info',
            table='borrow_info',
        ),
    ]
