# Generated by Django 4.1.7 on 2023-03-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_eq_borrow', '0002_alter_items_item_borrow_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_statuse',
            fields=[
                ('b_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facultie',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Id_type',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_note', models.TextField()),
                ('item_img_id', models.ImageField(upload_to='')),
                ('item_created_at', models.DateTimeField(auto_now_add=True)),
                ('item_updated_at', models.DateTimeField(auto_now=True)),
                ('item_borrow_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.borrow_statuse')),
            ],
        ),
        migrations.CreateModel(
            name='Item_categorie',
            fields=[
                ('item_cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_cate_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_statuse',
            fields=[
                ('item_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100, unique=True)),
                ('u_password', models.CharField(max_length=100)),
                ('u_email', models.EmailField(max_length=100)),
                ('u_tel', models.IntegerField()),
                ('u_created_at', models.DateTimeField(auto_now_add=True)),
                ('u_updated_at', models.DateTimeField(auto_now=True)),
                ('u_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.department')),
                ('u_faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.facultie')),
            ],
        ),
        migrations.CreateModel(
            name='User_privilege',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_borrow_status',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_department',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_faculty',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_id_type',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='u_department',
        ),
        migrations.RemoveField(
            model_name='users',
            name='u_faculty',
        ),
        migrations.RemoveField(
            model_name='users',
            name='u_privilege',
        ),
        migrations.DeleteModel(
            name='Borrow_statuses',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.DeleteModel(
            name='Id_types',
        ),
        migrations.DeleteModel(
            name='Item_categories',
        ),
        migrations.DeleteModel(
            name='Item_statuses',
        ),
        migrations.DeleteModel(
            name='User_privileges',
        ),
        migrations.AddField(
            model_name='user',
            name='u_privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.user_privilege'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.item_categorie'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.department'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.facultie'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.id_type'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.item_statuse'),
        ),
        migrations.AlterField(
            model_name='borrow_info',
            name='b_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_eq_borrow.item'),
        ),
        migrations.AlterField(
            model_name='borrow_info',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_eq_borrow.user'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
